### ISSUE TITLE
paddings

### ISSUE THREAD

**Issue by Theo-denBlanken** [Spyrincho/GridCSS#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/Spyrincho/GridCSS/blob/master/

Feedback: toevoegen[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by Spyrincho** [comment]
Alle documentatie is onderhand weer geupdate. Ik had alles af, en goed gedaan maar niet geüpload naar Github.
